# Generated by Django 3.2 on 2022-07-01 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='書籍名')),
                ('management_code', models.CharField(max_length=50, unique=True, verbose_name='管理番号')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部署名')),
            ],
        ),
        migrations.CreateModel(
            name='StaffInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='誕生日')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('at_desk', models.BooleanField(default=False, verbose_name='出社状態')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ビジネスネーム')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.department', verbose_name='所属部署')),
                ('information', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.staffinformation', verbose_name='社員情報')),
                ('rented_books', models.ManyToManyField(to='myapp2.Book', verbose_name='借りている本')),
            ],
        ),
    ]
