# Generated by Django 3.2 on 2022-06-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='誕生日')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('at_desk', models.BooleanField(default=False, verbose_name='出社状態')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ビジネスネーム')),
                ('information', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.staffinformation', verbose_name='社員情報')),
            ],
        ),
    ]
