# Generated by Django 3.2 on 2022-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='投稿者')),
                ('text', models.TextField(verbose_name='投稿内容')),
                ('date', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
    ]
